<?php

/*
		   8 8888       .8. `8.`888b                 ,8' d888888o.
		   8 8888      .888. `8.`888b               ,8'.`8888:' `88.
		   8 8888     :88888. `8.`888b             ,8' 8.`8888.   Y8
		   8 8888    . `88888. `8.`888b     .b    ,8'  `8.`8888.
		   8 8888   .8. `88888. `8.`888b    88b  ,8'    `8.`8888.
		   8 8888  .8`8. `88888. `8.`888b .`888b,8'      `8.`8888.
88.        8 8888 .8' `8. `88888. `8.`888b8.`8888'        `8.`8888.
`88.       8 888'.8'   `8. `88888. `8.`888`8.`88'     8b   `8.`8888.
  `88o.    8 88'.888888888. `88888. `8.`8' `8,`'      `8b.  ;8.`8888
	`Y888888 ' .8'       `8. `88888. `8.`   `8'        `Y8888P ,88P'

	JIGSAW ACADEMY WORKFLOW SYSTEM v1
	---------------------------------
*/

	// Prevent exclusive access
	if (!defined("JAWS")) {
		header('Location: ../index.php');
		die();
	}

	// This task is executed to remind users of their unused customized paylinks.
	// This is a taken up by a daily CRON job
	// REMOVE THE FOLLOWING LINE TO MAKE IT LIVE !!! ------------------------------------------ << ==================
	$GLOBALS['jaws_exec_live'] = false;

	// Load Stuff
	load_library("email");
	load_module("course");
	load_module("subs");

	// Query - Get all unused links generated by an agent (user) for all users, 3/7 days ago.
	$clinks = db_query('
			SELECT
				link.user_id AS user_id,
				link.paylink_id AS paylink_id,
				link.web_id AS web_id,
				link.create_date AS create_date,
				link.subs_id AS subs_id
			FROM
				payment_link AS link
			INNER JOIN
				payment_instl AS instl
				ON instl.instl_id = link.instl_id
			WHERE
				link.create_entity_type = "user" AND
				link.status = "enabled" AND
				((
						DATE(link.create_date) > DATE_SUB(CURDATE(), INTERVAL 3 DAY) AND
						DATE(link.create_date) <= DATE_SUB(CURDATE(), INTERVAL 2 DAY) AND
					) OR (
						DATE(link.create_date) > DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND
						DATE(link.create_date) <= DATE_SUB(CURDATE(), INTERVAL 6 DAY) AND
				)) AND
				instl.instl_count = 1
			GROUP BY
				link.user_id
			ORDER BY
				link.create_date ASC;
		');

	// For each of the users, see if a more recent link generated was (by website and used) OR (by agent)
	// if not, send reminder

	if (!isset($clinks[0])) exit();
	foreach($clinks as $clink) {

		$worclink = db_query('
				SELECT
					*
				FROM
					payment_link AS link
				INNER JOIN
					payment_instl AS instl
					ON instl.instl_id = link.instl_id
				WHERE
					((
							link.create_entity_type="system" AND
							link.status = "used"
						) OR (
							link.create_entity_type="user"
					)) AND
					link.paylink_id > "'.$clink['paylink_id'].'" AND
					instl.instl_count = 1 AND
					link.user_id = '.$clink['user_id'].';
			');

		// If payment happened OR a newer link was sent
		if (isset($worclink[0])) continue;

		// Prep
		$paylink_info = payment_link_parse($clink['web_id']);
		$user = user_get_by_id($clink['user_id']);
		$subs = subs_get_info($clink["subs_id"]);
		$combo_str = $subs["combo"].";".$subs["combo_free"];
		$combo_arr = course_get_combo_arr($combo_str);
		$combo_arr_free_exclusive = course_get_combo_arr($subs["combo_free"]);
		$sc_str = "";
		$price_str = "";

		$course;
		$count = 0;
		foreach($combo_arr as $course_id => $learn_mode) {

			$res = db_query("SELECT * FROM course WHERE course_id=".$course_id." LIMIT 1;");
			$res_meta = db_query("SELECT * FROM course_meta WHERE course_id=".$course_id." LIMIT 1;");

			if (!isset($res[0]["name"])) continue;
			if (!isset($res_meta[0])) continue;

			$course_content = json_decode($res_meta[0]["content"], true);

			$course[$count]["name"] = $res[0]["name"];
			$course[$count]["learn_mode"] = ((strcmp($learn_mode, "1") == 0)? "Premium" : "Regular");
			$course[$count]["desc"] = $res_meta[0]["desc"];
			$course[$count]["img"] = $course_content["img_main_small"];
			$course[$count]["url"] = $course_content["url_web"];

			if (isset($combo_arr_free_exclusive[$course_id])) $course[$count]["free"] = true;
			else $course[$count]["free"] = false;

			$sc_str .= ((strcmp($learn_mode, "1") == 0)? $res[0]["il_code"] : $res[0]["sp_code"]).",";
			$price_str .= ((strcmp($learn_mode, "1") == 0)? $res[0]["il_price_inr"] : $res[0]["sp_price_inr"]).",";

			$count ++;
		}

		// Prep More
		$content["user_webid"] = $user["web_id"];
		$content["paylink_id"] = $clink['web_id'];
		$content["fname"] = substr($user["name"], 0, ((strpos($user["name"], " ") !== false) ? strpos($user["name"], " ") : strlen($user["name"])));
		$content["sum"] = $paylink_info["sum"];
		$content["currency"] = $paylink_info["currency"];
		$content["courses"] = $course;
		$content["payment"] = payment_get_info($paylink_info["pay_id"]);
		if ((!isset($user["lms_soc"])) || (strlen($user["lms_soc"]) == 0)) $content["allow_setup"] = true;
		else $content["allow_setup"] = false;

		// Send follow-up reminde
		send_email('subs.init.followup', array("to" => 'sreepati@jigsawacademy.com'), $content);

	}

	// All done
	die();

?>
