<?php

/*
           8 8888       .8. `8.`888b                 ,8' d888888o.   
           8 8888      .888. `8.`888b               ,8'.`8888:' `88. 
           8 8888     :88888. `8.`888b             ,8' 8.`8888.   Y8 
           8 8888    . `88888. `8.`888b     .b    ,8'  `8.`8888.     
           8 8888   .8. `88888. `8.`888b    88b  ,8'    `8.`8888.    
           8 8888  .8`8. `88888. `8.`888b .`888b,8'      `8.`8888.   
88.        8 8888 .8' `8. `88888. `8.`888b8.`8888'        `8.`8888.  
`88.       8 888'.8'   `8. `88888. `8.`888`8.`88'     8b   `8.`8888. 
  `88o.    8 88'.888888888. `88888. `8.`8' `8,`'      `8b.  ;8.`8888 
    `Y888888 ' .8'       `8. `88888. `8.`   `8'        `Y8888P ,88P' 

    JIGSAW ACADEMY WORKFLOW SYSTEM v2
    ---------------------------------
*/

  	// Prevent exclusive access
	if (!defined("JAWS")) {
		header('Location: https://www.jigsawacademy.com');
		die();
	}

    	// Load stuff
    	load_module("iot");

    	// Init View
    	iot_view_init();
  
?>

  <!-- HTML HEAD -->
  <?php 
	$GLOBALS["content"]["title"] = "The Next Big Revolution";
	load_template("iot", "v1/head");
  ?>
  <!-- HTML HEAD ENDS -->

  <!-- HEADER MENU -->
  <?php load_template("iot", "v1/header"); ?>
  <!-- HEADER MENU ENDS -->

<!-- Banner Start -->
<div class="gray-bg" id="side_nav_item_id_0">
  <div class="wrapper header-padding-top">
	<div class="row">
	  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<h1 class="innerpage-banner-title f-color-blue">IoT Specialization</h1>
		<p class="banner-contain">An extremely comprehensive course which makes you the most sought after Internet of Things professional.</p>
		<div class="margin-30"></div>
		<div class="row">
		  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="pull-left">
			  <h3 class="cancel-prize"> <strike><i class="fa fa-inr" aria-hidden="true"></i>85,000</strike> </h3>
			  <h1 class="prize"><i class="fa fa-inr" aria-hidden="true"></i>65,000<span class="taxes-text">+ taxes </span> </h1>
			</div>
			<div class="innerpage-btn-margin pull-left">
			 <?php //if (!auth_session_is_logged()) { ?>	
			 	<!--<a href="#" class="text-capitalize skew-fill-color innerpage-btn" data-toggle="modal" data-target="#loginmodal">Sign Up</a> -->
			 <?php //} else { ?>
				<a href="#" class="text-capitalize skew-fill-color innerpage-btn">Enroll Now</a> 
			 <?php //} ?>
			</div>
		  </div>
		</div>
	  </div>
	  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="margin-30 hidden-lg hidden-md hidden-sm"></div>
		<div class="header-img-margin hidden-xs"> <img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/specialization-header.jpg" class="img-responsive"> </div>
	  </div>
	</div>
  </div>
</div>
<!-- Banner End --> 

<!-- submenu start -->
<div class="nav-scrolling hidden-xs">
  <div class="wrapper">
	<nav class="navbar navbar-default navbar-custom ">
	  <ul class="nav navbar-nav pull-left">
		<li><a href="#about-section" class="cool-link">ABOUT THIS SPECIALIZATION</a></li>
		<li><a href="#key-feature-section" class="cool-link">key features</a></li>
		<li><a href="#courses-section" class="cool-link">COURSES INCLUDED</a></li>
		<li><a href="#you-get-section" class="cool-link">WHAT YOU will GET</a></li>
	  </ul>
	</nav>
  </div>
</div>

<!-- submenu end --> 

<!-- about section start -->
<div class="wrapper section-padding-top section-padding-bottom" id="about-section">
  <div class="row hidden-lg hidden-md hidden-sm">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	  <h2 class="innerpage-title">About this Specialization</h2>
	  <div class="gary-strip"></div>
	</div>
  </div>
  <div class="conatin-margin-top hidden-lg hidden-md hidden-sm"></div>
  <div class="row">
	<div class="col-lg-8 col-md-8 col-sm-8 padding-right-30">
	  <p>This specialization will help you, learn to build IoT devices using the Arduino and the Raspberry Pi platforms understand, how IoT works with the cloud, and analyze the data generated by the IoT devices. On completion, participants will be able to develop and implement their own IoT technologies, solutions and applications.</p>
	  <br>
	  <p>This integrated specialization is aimed at working professionals seeking to expand their understanding of the field or at beginners looking for a thorough grounding in the various technologies associated with this field. </p>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-4 border-left-side padding-left-40">
	  <p><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/prerequisites.png"> &nbsp; <span class="capital f-color-blue">prerequisites:</span></p>
	  <p class="padding-left-27">Basic programming skills</p>
	  <p><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/courses.png"> &nbsp; <span class="capital f-color-blue">courses:</span> 5</p>
	  <p><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/Calendar.png"> &nbsp; <span class="capital f-color-blue">duration:</span> 30 Hrs.</p>
	  <p><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/capstone-projects.png"> &nbsp; <span class="capital f-color-blue">capstone-projects:</span> 4</p>
	</div>
  </div>
</div>

<!-- about section end --> 

<!-- keyfeature section start -->
<div class="border-top">
  <div class="wrapper section-padding-top section-padding-bottom" id="key-feature-section">
	<div class="row">
	  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<h2 class="innerpage-title">Key Features</h2>
		<div class="gary-strip"></div>
	  </div>
	</div>
	<div class="row conatin-margin-top">
	  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<p><span><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/check-icn.png"></span> &nbsp;&nbsp; Most comprehensive course in IOT to date</p>
		<p><span><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/check-icn.png"></span> &nbsp;&nbsp; Learning by doing -  Very high emphasis on practical learning</p>
		<p><span><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/check-icn.png"></span> &nbsp;&nbsp; Only Specialization integrating Analytics and Big Data with IoT concepts</p>
		<p><span><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/check-icn.png"></span> &nbsp;&nbsp; IoT Hardware Kit as a part of the course</p>
		<p><span><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/check-icn.png"></span> &nbsp;&nbsp; Course designed by IoT practitioners</p>
		<p><span><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/check-icn.png"></span> &nbsp;&nbsp; Makes you IOT ready professional</p>
		<p><span><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/check-icn.png"></span> &nbsp;&nbsp; Suitable for both hardware and software professional</p>
	  </div>
	</div>
  </div>
</div>
<!-- keyfeature section start --> 

<!-- courses section start -->
<div class="gray-bg" id="courses-section">
  <div class="wrapper section-padding-top section-padding-bottom">
	<div class="row">
	  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<h2 class="innerpage-title">Courses Included</h2>
		<div class="gary-strip"></div>
	  </div>
	</div>
	<div class="row section-padding-top">
	  <div id="owl-demo">
		<div class="owl-item">
		  <div class="specialization-box1 specialization-box relative">
			<div class="specialization-box-circle light-blue-bg center">
			  <h2 class="white-text font-size-25">01</h2>
			</div>
			<h4 class="specialization-box-title center">IoT for Beginners</h4>
			<p class="specialization-box-contain center">Get an overview of the phenomenon called the Internet of Things</p>
		  </div>
		</div>
		<div class="owl-item">
		  <div class="specialization-box2 specialization-box relative">
			<div class="specialization-box-circle light-orange-bg center">
			  <h2 class="white-text font-size-25">02</h2>
			</div>
			<h4 class="specialization-box-title center">IOT from the Ground Up -Using Arduino</h4>
			<p class="specialization-box-contain center">Build IoT projects with microcontrollers and sensors and connect them to cloud</p>
		  </div>
		</div>
		<div class="owl-item">
		  <div class="specialization-box3 specialization-box relative">
			<div class="specialization-box-circle light-blue-bg center">
			  <h2 class="white-text font-size-25">03</h2>
			</div>
			<h4 class="specialization-box-title center">Powering the IoT - Using Raspberry Pi</h4>
			<p class="specialization-box-contain center">Develop complex IoT applications by focusing on high level operating systems</p>
		  </div>
		</div>
		<div class="owl-item">
		  <div class="specialization-box4 specialization-box relative">
			<div class="specialization-box-circle light-orange-bg center">
			  <h2 class="white-text font-size-25">04</h2>
			</div>
			<h4 class="specialization-box-title center">IoT and the Cloud</h4>
			<p class="specialization-box-contain center">Understanding Cloud Computing and its relation to IoT </p>
		  </div>
		</div>
		<div class="owl-item">
		  <div class="specialization-box5 specialization-box relative">
			<div class="specialization-box-circle light-blue-bg center">
			  <h2 class="white-text font-size-25">05</h2>
			</div>
			<h4 class="specialization-box-title center">Analytics of Things</h4>
			<p class="specialization-box-contain center">Logical step to IoT -  Analytics of the Internet of Things</p>
		  </div>
		</div>
	  </div>
	</div>
  </div>
</div>
<!-- courses section end --> 

<!-- youget section start -->
<div class="wrapper section-padding-top section-padding-bottom" id="you-get-section">
  <div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	  <h2 class="innerpage-title">What Will You Get?</h2>
	  <div class="gary-strip"></div>
	</div>
  </div>
  <div class="row section-padding-top">
	<div class="col-lg-1 col-md-1 col-sm-12 col-xs-12"> </div>
	<div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
	  <div class="row">
		<div class="col-lg-2 col-md-2 col-sm-3 col-xs-2">
		  <div class="dark-blue-bg specialization-small-circle"><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/hardwarekit-icn.png"></div>
		</div>
		<div class="col-lg-10 col-md-10 col-sm-9 col-xs-10">
		  <p>
		  <h4>IoT Hardware Kit</h4>
		  </p>
		  <p class="feature-contain">Get Arduino and Raspberry Pi along with WiFi Dongle, Webcam, Sensor modules and other accessories</p>
		</div>
	  </div>
	</div>
	<div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
	  <div class="conatin-margin-top hidden-lg hidden-md hidden-sm"></div>
	  <div class="row">
		<div class="col-lg-2 col-md-2 col-sm-3 col-xs-2">
		  <div class="light-orange-bg specialization-small-circle"><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/pre-recorded-icn.png"></div>
		</div>
		<div class="col-lg-10 col-md-10 col-sm-9 col-xs-10">
		  <p>
		  <h4>Pre-recorded Lectures</h4>
		  </p>
		  <p class="feature-contain">View 30 hours of video lectures, as often as you want</p>
		</div>
	  </div>
	</div>
	<div class="col-lg-1 col-md-1 col-sm-12 col-xs-1"> </div>
  </div>
  <div class="row conatin-margin-top">
	<div class="col-lg-1 col-md-1 col-sm-12 col-xs-12"> </div>
	<div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
	  <div class="row">
		<div class="col-lg-2 col-md-2 col-sm-3 col-xs-2">
		  <div class="light-green-bg specialization-small-circle"><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/learning-centre-icn.png"></div>
		</div>
		<div class="col-lg-10 col-md-10 col-sm-9 col-xs-10">
		  <p>
		  <h4>Jigsaw Learning Centre</h4>
		  </p>
		  <p class="feature-contain">Gain free access to a variety of supplemental resources like handouts, reference material, guides, lecture transcripts and student forums</p>
		</div>
	  </div>
	</div>
	<div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
	  <div class="conatin-margin-top hidden-lg hidden-md hidden-sm"></div>
	  <div class="row">
		<div class="col-lg-2 col-md-2 col-sm-3 col-xs-2">
		  <div class="light-blue-bg specialization-small-circle"><img src="<?php echo $_SERVER['server_name'].'/'.JAWS_PATH_LOCAL.'/common/iot/'; ?>images/faculty-support-icn.png"></div>
		</div>
		<div class="col-lg-10 col-md-10 col-sm-9 col-xs-10">
		  <p>
		  <h4>Faculty Support</h4>
		  </p>
		  <p class="feature-contain">Get your doubts solved by the Jigsaw Faculty via email, phone or chat</p>
		</div>
	  </div>
	</div>
	<div class="col-lg-1 col-md-1 col-sm-12 col-xs-12"> </div>
  </div>
</div>
<!-- youget section end --> 

	<!-- FOOTER -->
	<?php load_template("iot", "v1/footer"); ?>
	<!-- FOOTER ENDS -->

	<!-- LOGIN MODAL -->
	<?php load_template("iot", "v1/login"); ?>
	<!-- LOGIN MODAL ENDS -->

<script>
var menu = document.querySelector('.menu');
function toggleMenu () {
  menu.classList.toggle('open');
}
menu.addEventListener('click', toggleMenu);
</script> 

<script>
$(document).ready(function() {
 
  $("#owl-demo").owlCarousel({ 
	  autoPlay: 5000, //Set AutoPlay to 5 seconds 
	  items : 3,
	  itemsDesktop : [1199,3],
	  itemsDesktopSmall : [979,2]
 
  });
 
});
</script>
</body>
</html>