<?php header("Content-type: application-xml"); ?>
<?xml version="1.0" encoding="utf-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <url>
    <loc>https://www.jigsawacademy.com/iot/home</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/video.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/down-arrow.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/box-icn1.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/box-icn2.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/box-icn3.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/IoT_home_6.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Connected-Smart-Cities.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/testimonial02.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/testimonial03.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/testimonial04.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/testimonial05.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/specialization-gray-design.png</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/long-arrow.png</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-video-white.png</image:loc>
        <image:title>video</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/announcement.png</image:loc>
        <image:title>announcement</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-candidate.svg</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-map.svg</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-rupee.svg</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-brochure.png</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/bottom-arrow.png</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Vicky-Crasto-170x140.jpg</image:loc>
        <image:title>Vicky Crasto</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Yamini-Pandari-170x140.jpg</image:loc>
        <image:title>Yamini Pandari</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Niranjanprasad-Bhagwat-170x140.png</image:loc>
        <image:title>Niranjanprasad Bhagwat</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/long-arrow-white.png</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/executive-programs-banner.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/03/Logo_unit-1.png</image:loc>
        <image:title>Logo</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/begines-img.png</image:loc>
        <image:title>img</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/application-img.png</image:loc>
        <image:title>img</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-cap.png</image:loc>
        <image:title>img</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/num1.png</image:loc>
        <image:title>num</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/num2.png</image:loc>
        <image:title>num</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/num3.png</image:loc>
        <image:title>num</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/08/McKinsey_Logo1-300x33.png</image:loc>
        <image:title>McKinsey_Logo1</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/cognizent-184x92.png</image:loc>
        <image:title>cognizent</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/swiss-re1-184x92.png</image:loc>
        <image:title>swiss re</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/HCL1-184x92.png</image:loc>
        <image:title>HCL</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/societe-generale-184x92.png</image:loc>
        <image:title>societe generale</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/maersk-184x92.png</image:loc>
        <image:title>maersk</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/flipkart-184x92.png</image:loc>
        <image:title>flipkart</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/mahindra-184x92.png</image:loc>
        <image:title>mahindra</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/wipro-184x92.png</image:loc>
        <image:title>wipro</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/01/Gramener-184x92.png</image:loc>
        <image:title>Gramener</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/03/et2.jpg</image:loc>
        <image:title>et2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/03/DH.jpg</image:loc>
        <image:title>DH</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/09/THE_WEEK_logo2.jpg</image:loc>
        <image:title>THE_WEEK_logo2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/et2.jpg</image:loc>
        <image:title>et2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/hindu.png</image:loc>
        <image:title>hindu</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/CXO-Today.jpg</image:loc>
        <image:title>CXO-Today</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/14-Why-learning-both-SAS-R-can-do-wonders-for-your-career-300x145.png</image:loc>
        <image:title>14-Why learning both SAS &amp; R can do wonders for your career</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/4-5-essential-skills-for-a-big-data-analyst-300x145.png</image:loc>
        <image:title>4-5 essential skills for a big data analyst</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/1-What-is-analytics-300x145.png</image:loc>
        <image:title>1-What-is-analytics</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/8-Do-programmers-have-it-easier-when-it-comes-to-analytics1-300x145.png</image:loc>
        <image:title>8-Do-programmers-have-it-easier-when-it-comes-to-analytics</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/iot/introduction-to-iot-analytics</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/four_five_star.png</image:loc>
        <image:title>4.4 Star Rating: Very Good</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/prerequisites.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Monitor.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Calendar.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key6.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/capstone-project-icon.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-Hardware-Kit.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Catalyst.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Jigsaw-Learning-Center.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Faculty-Support.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-harikrishna.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-urmil.jpg</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/why-learning-both-sas-r-can-do-wonders-for-your-career/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/view-icon-white.png</image:loc>
        <image:title>comment</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/14-Why-learning-both-SAS-R-can-do-wonders-for-your-career-400x222.png</image:loc>
        <image:title>14-Why learning both SAS &amp; R can do wonders for your career</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/4-5-essential-skills-for-a-big-data-analyst-400x222.png</image:loc>
        <image:title>4-5 essential skills for a big data analyst</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/1-What-is-analytics-400x222.png</image:loc>
        <image:title>1-What-is-analytics</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/8-Do-programmers-have-it-easier-when-it-comes-to-analytics1-400x222.png</image:loc>
        <image:title>8-Do-programmers-have-it-easier-when-it-comes-to-analytics</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/about-us/careers/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/team.jpe</image:loc>
        <image:title>img</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/temp/small-arrow-orange.png</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/temp/long-arrow-orange.png</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-upload.png</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/success-stories-video-banner.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/star.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/hat.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Vicky-Crasto-170x140.jpg</image:loc>
        <image:title>Vicky Crasto</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Yamini-Pandari-170x140.jpg</image:loc>
        <image:title>Yamini Pandari</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Niranjanprasad-Bhagwat-170x140.png</image:loc>
        <image:title>Niranjanprasad Bhagwat</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Vicky-Crasto-441x247.jpg</image:loc>
        <image:title>Vicky Crasto</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/in-img.png</image:loc>
        <image:title>linkedin</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Niranjanprasad-Bhagwat-490x247.png</image:loc>
        <image:title>Niranjanprasad Bhagwat</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/in-img2.png</image:loc>
        <image:title>linkedin</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/05/Jha-153x140.png</image:loc>
        <image:title>Jha</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/04/IMG_0174.jpg</image:loc>
        <image:title>IMG_0174</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Rachit-Khanna-170x140.jpg</image:loc>
        <image:title>Rachit Khanna</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/smriti-170x140.jpe</image:loc>
        <image:title>smriti</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Rajesh-170x140.jpg</image:loc>
        <image:title>Rajesh</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/Saurabh-170x140.png</image:loc>
        <image:title>Saurabh</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Ashish-Jain1-e1452491602683-170x140.jpg</image:loc>
        <image:title>Ashish Jain</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Nakul-Dogra-170x140.jpg</image:loc>
        <image:title>Nakul Dogra</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Clarence-Wong_2-170x140.png</image:loc>
        <image:title>Clarence Wong_2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Ganapathy-170x140.jpg</image:loc>
        <image:title>Ganapathy</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Kaushik-Anantharaman-170x140.jpg</image:loc>
        <image:title>Kaushik Anantharaman</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Avinash-Sri-Raja-Gopal_2-170x140.jpg</image:loc>
        <image:title>Avinash Sri Raja Gopal_2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/short-icon-share-lg-white.png</image:loc>
        <image:title>arrow</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/online-analytics-training/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/compare-image.png</image:loc>
        <image:title>compare</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/Compare-Chart-3.jpg</image:loc>
        <image:title>HR Analyst</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/short-icon-share-lg-white.png</image:loc>
        <image:title>arrow</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/resources/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/IoT-India-Salary-Study-2017_IoT-India-Magazine_Jigsaw-Academy_Page_01.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-download.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Jigsaw-Academy-Analytics-Industry-Report-2017-1_Page_01.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Beginners-Guide.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/icon611.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/salary-report1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/EXCEL-EBOOK-IMAGE.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/SHARAN.jpg</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/web-analytics-training/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/three_five_star.png</image:loc>
        <image:title>three_five_star</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/education_icon.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/62.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/23.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/71.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/32.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/83.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/42.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/9.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/52.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/10.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/43.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/111.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/24.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/12.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/13.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Certificate-Final-Web-Analytics1.png</image:loc>
        <image:title>Certificate - Final-Web Analytics</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Praful-Tickoo-170x140.png</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/fraud-analytics-course/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/212.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/117.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/12/SAS-to-HADOOP.png</image:loc>
        <image:title>Language of SAS Code</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/12/Program-Videos.png</image:loc>
        <image:title>Lab Time (optional)</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Certificate-Final-Fraud-Analytics1.png</image:loc>
        <image:title>Certificate - Final-Fraud Analytics</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/smriti-170x140.jpe</image:loc>
        <image:title>smriti</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/niranjan-prasad-bhagwat/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Niranjanprasad-Bhagwat-170x140.png</image:loc>
        <image:title>Niranjanprasad Bhagwat</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/in-img3-w.png</image:loc>
        <image:title>linkedin</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/iot/iot-courses</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/specialization_professional.jpg</image:loc>
        <image:title>Professional IoT Training</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/specialization-course-number.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/specialization-duration.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/specialization_analyst.jpg</image:loc>
        <image:title>IoT Analyst Certification</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/specialization_expert.jpg</image:loc>
        <image:title>Advanced IoT Analytics Certification</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-for-Beginners.jpg</image:loc>
        <image:title>IoT for Beginners</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-from-the-Ground-Up.jpg</image:loc>
        <image:title>IoT Using Arduino</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Powering-the-IOT.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Basics-of-Javascript.png</image:loc>
        <image:title>Basics of Javascript Training</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-and-the-Cloud.jpg</image:loc>
        <image:title>IoT and the Cloud Training</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-Analytics-1.jpg</image:loc>
        <image:title>IoT Analyst Certification Courses</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-Analytics-2.jpg</image:loc>
        <image:title>Data Science for IoT Training</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/specialization-img.jpg</image:loc>
        <image:title>Advanced IoT Analytics Courses</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Certificate-Final-IOT.jpg</image:loc>
        <image:title>IoT Certification</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Certificate-Final-IOT-Analyst.jpg</image:loc>
        <image:title>IoT Certification</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Certificate-Final-IOT-Professional.jpg</image:loc>
        <image:title>IoT Certification for Professionals</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-Hardware-Kit.png</image:loc>
        <image:title>IoT Hardware Kit</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Catalyst.png</image:loc>
        <image:title>IoT Pre-Recorded Lectures</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Jigsaw-Learning-Center.png</image:loc>
        <image:title>Jigsaw Academy's IoT Training</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Faculty-Support.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-harikrishna.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-srinivas.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-urmil.jpg</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/contact/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/get-direction-img.png</image:loc>
        <image:title>img</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/text-mining-with-r/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/four_star.png</image:loc>
        <image:title>four_star</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/education_icon.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/57.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/27.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/19.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/46.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/35.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Certificate-Final-Text-mining-with-R1.png</image:loc>
        <image:title>Certificate - Final-Text mining with R</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Karthik-170x140.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Waghmare-170x140.jpg</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/apache-spark/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/03/4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/03/6.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/03/1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/03/5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/03/7.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/03/2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/03/9.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/03/8.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/03/3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/03/Certificate-Final-Apache-spark.png</image:loc>
        <image:title>Certificate - Final-Apache spark</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/big-data-for-beginners/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/four_seven_star.png</image:loc>
        <image:title>four_seven_star</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/education_icon.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/6.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/7.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/Certificate-Final-BD-for-Beginners3.png</image:loc>
        <image:title>Certificate - Final-BD for Beginners</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Avinash-Sri-Raja-Gopal_2-170x140.jpg</image:loc>
        <image:title>Avinash Sri Raja Gopal_2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Ganapathy-170x140.jpg</image:loc>
        <image:title>Ganapathy</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/iot/data-science-for-iot</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/three_nine_star.png</image:loc>
        <image:title>3.9 Star Rating: Very Good</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/prerequisites.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Monitor.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Calendar.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key6.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Icons_Inferential_Data_Analytics_for_IoT.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Icons_Predictive_IoT_analytics_via_IoT_Data_Classification.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Icons_Prescriptive_IoT_Data_Analytics_for_IoT.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Icons_IoT_Case_Study_Air_Quality_Data.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/capstone-project-icon.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-Hardware-Kit.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Catalyst.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Jigsaw-Learning-Center.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Faculty-Support.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-harikrishna.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-urmil.jpg</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/rachit/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Rachit-Khanna-170x140.jpg</image:loc>
        <image:title>Rachit Khanna</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/supply-chain/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/6.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/8.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/9.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/11.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/14.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/13.png</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/rajesh-ramamurthy/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Rajesh-170x140.jpg</image:loc>
        <image:title>Rajesh</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/iot/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/video.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/down-arrow.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/box-icn1.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/box-icn2.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/box-icn3.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/IoT_home_6.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Connected-Smart-Cities.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/testimonial02.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/testimonial03.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/testimonial04.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/testimonial05.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/specialization-gray-design.png</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/clarence-wong-2/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Clarence-Wong_2-170x140.png</image:loc>
        <image:title>Clarence Wong_2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/in-img3-w.png</image:loc>
        <image:title>linkedin</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/corporate-training-analytics/analytics-recruitment/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-video-white.png</image:loc>
        <image:title>video</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/12/SAS-to-HADOOP.png</image:loc>
        <image:title>logo</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/smriti-170x140.jpe</image:loc>
        <image:title>smriti</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/what-is-analytics/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/view-icon-white.png</image:loc>
        <image:title>comment</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/14-Why-learning-both-SAS-R-can-do-wonders-for-your-career-400x222.png</image:loc>
        <image:title>14-Why learning both SAS &amp; R can do wonders for your career</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/4-5-essential-skills-for-a-big-data-analyst-400x222.png</image:loc>
        <image:title>4-5 essential skills for a big data analyst</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/1-What-is-analytics-400x222.png</image:loc>
        <image:title>1-What-is-analytics</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/8-Do-programmers-have-it-easier-when-it-comes-to-analytics1-400x222.png</image:loc>
        <image:title>8-Do-programmers-have-it-easier-when-it-comes-to-analytics</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/executive-programs/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/executive-programs-banner.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/03/Logo_unit-1.png</image:loc>
        <image:title>Logo</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/begines-img.png</image:loc>
        <image:title>img</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/application-img.png</image:loc>
        <image:title>img</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-cap.png</image:loc>
        <image:title>img</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/iot/iot-using-arduino</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/three_nine_star.png</image:loc>
        <image:title>4 Star Rating: Very Good</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/prerequisites.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Monitor.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Calendar.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key6.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/capstone-project-icon.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-Hardware-Kit.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Catalyst.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Jigsaw-Learning-Center.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Faculty-Support.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-harikrishna.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-urmil.jpg</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/r-analytics-training/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/education_icon.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Rajesh-170x140.jpg</image:loc>
        <image:title>Rajesh</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Clarence-Wong_2-170x140.png</image:loc>
        <image:title>Clarence Wong_2</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/big-data-training/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Avinash-Sri-Raja-Gopal_2-170x140.jpg</image:loc>
        <image:title>Avinash Sri Raja Gopal_2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Ganapathy-170x140.jpg</image:loc>
        <image:title>Ganapathy</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/vicky-crasto/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Vicky-Crasto-170x140.jpg</image:loc>
        <image:title>Vicky Crasto</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/in-img3-w.png</image:loc>
        <image:title>linkedin</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/retail-analytics/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/three_nine_star.png</image:loc>
        <image:title>three_nine_star</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/education_icon.png</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/kaushik-ananthraman/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Kaushik-Anantharaman-170x140.jpg</image:loc>
        <image:title>Kaushik Anantharaman</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/in-img3-w.png</image:loc>
        <image:title>linkedin</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/financial-analytics/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/education_icon.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Rachit-Khanna-170x140.jpg</image:loc>
        <image:title>Rachit Khanna</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/smriti-170x140.jpe</image:loc>
        <image:title>smriti</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/iot/iot-beginners-course</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/four_five_star.png</image:loc>
        <image:title>4.6 Star Rating: Very Good</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/prerequisites.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Monitor.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Calendar.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-1.png</image:loc>
        <image:title>IoT Introduction for Beginners</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-2.png</image:loc>
        <image:title>Working with IoT</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-3.png</image:loc>
        <image:title>Get Started with IoT</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/iot/iot-javascript</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/three_nine_star.png</image:loc>
        <image:title>4 Star Rating: Very Good</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/prerequisites.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Monitor.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Calendar.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-Hardware-Kit.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Catalyst.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Jigsaw-Learning-Center.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Faculty-Support.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-harikrishna.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-urmil.jpg</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/big-data-specialist/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Avinash-Sri-Raja-Gopal_2-170x140.jpg</image:loc>
        <image:title>Avinash Sri Raja Gopal_2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Ganapathy-170x140.jpg</image:loc>
        <image:title>Ganapathy</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/bocconi-business-analytics-program-mumbai/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-candidate.svg</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-map.svg</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-rupee.svg</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-brochure.png</image:loc>
        <image:title>arrow</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Kaushik-Anantharaman-170x140.jpg</image:loc>
        <image:title>Kaushik Anantharaman</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/05/Jha-153x140.png</image:loc>
        <image:title>Jha</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/5-essential-skills-every-big-data-analyst-should-have/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/view-icon-white.png</image:loc>
        <image:title>comment</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/14-Why-learning-both-SAS-R-can-do-wonders-for-your-career-400x222.png</image:loc>
        <image:title>14-Why learning both SAS &amp; R can do wonders for your career</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/4-5-essential-skills-for-a-big-data-analyst-400x222.png</image:loc>
        <image:title>4-5 essential skills for a big data analyst</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/1-What-is-analytics-400x222.png</image:loc>
        <image:title>1-What-is-analytics</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/8-Do-programmers-have-it-easier-when-it-comes-to-analytics1-400x222.png</image:loc>
        <image:title>8-Do-programmers-have-it-easier-when-it-comes-to-analytics</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/ganapathy-2/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Ganapathy-170x140.jpg</image:loc>
        <image:title>Ganapathy</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/hr-analytics-courses/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/education_icon.png</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/about-us/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/03/et2.jpg</image:loc>
        <image:title>et2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/03/DH.jpg</image:loc>
        <image:title>DH</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/09/THE_WEEK_logo2.jpg</image:loc>
        <image:title>THE_WEEK_logo2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/et2.jpg</image:loc>
        <image:title>et2</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/hindu.png</image:loc>
        <image:title>hindu</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/CXO-Today.jpg</image:loc>
        <image:title>CXO-Today</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/smriti/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/smriti-170x140.jpe</image:loc>
        <image:title>smriti</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/iot/iot-cloud</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/three_nine_star.png</image:loc>
        <image:title>4 Star Rating: Very Good</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/prerequisites.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Monitor.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Calendar.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key6.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-Hardware-Kit.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Catalyst.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Jigsaw-Learning-Center.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Faculty-Support.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-harikrishna.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-urmil.jpg</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/kanav/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/in-img3-w.png</image:loc>
        <image:title>linkedin</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/online-sas-training/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/four_five_star.png</image:loc>
        <image:title>four_five_star</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/education_icon.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Ashish-Jain1-e1452491602683-170x140.jpg</image:loc>
        <image:title>Ashish Jain</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/smriti-170x140.jpe</image:loc>
        <image:title>smriti</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Rachit-Khanna-170x140.jpg</image:loc>
        <image:title>Rachit Khanna</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/yamini-pandari/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Yamini-Pandari-170x140.jpg</image:loc>
        <image:title>Yamini Pandari</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/avinash-gopal/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Avinash-Sri-Raja-Gopal_2-170x140.jpg</image:loc>
        <image:title>Avinash Sri Raja Gopal_2</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/about-us/people/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/in-img.png</image:loc>
        <image:title>linkedin</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/in-img2.png</image:loc>
        <image:title>linkedin</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/articles/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/4-5-essential-skills-for-a-big-data-analyst-400x222.png</image:loc>
        <image:title>4-5 essential skills for a big data analyst</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/1-What-is-analytics-400x222.png</image:loc>
        <image:title>1-What-is-analytics</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/14-Why-learning-both-SAS-R-can-do-wonders-for-your-career-400x222.png</image:loc>
        <image:title>14-Why learning both SAS &amp; R can do wonders for your career</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/8-Do-programmers-have-it-easier-when-it-comes-to-analytics1-400x222.png</image:loc>
        <image:title>8-Do-programmers-have-it-easier-when-it-comes-to-analytics</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/ashish-jain-2/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Ashish-Jain1-e1452491602683-170x140.jpg</image:loc>
        <image:title>Ashish Jain</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/financial-analytics-specialization/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/smriti-170x140.jpe</image:loc>
        <image:title>smriti</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Clarence-Wong_2-170x140.png</image:loc>
        <image:title>Clarence Wong_2</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/how-online-training-works/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/num2.png</image:loc>
        <image:title>num</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/num3.png</image:loc>
        <image:title>num</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Rachit-Khanna-170x140.jpg</image:loc>
        <image:title>Rachit Khanna</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Rajesh-170x140.jpg</image:loc>
        <image:title>Rajesh</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/analytics-for-beginners/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/education_icon.png</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/data-science-training/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Rachit-Khanna-170x140.jpg</image:loc>
        <image:title>Rachit Khanna</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/10/Rajesh-170x140.jpg</image:loc>
        <image:title>Rajesh</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/explore-analytics/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Vicky-Crasto-170x140.jpg</image:loc>
        <image:title>Vicky Crasto</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Yamini-Pandari-170x140.jpg</image:loc>
        <image:title>Yamini Pandari</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/10/Niranjanprasad-Bhagwat-170x140.png</image:loc>
        <image:title>Niranjanprasad Bhagwat</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Beginners-Guide.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/icon-download.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/icon611.png</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/iot/iot-career</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/box-icn1.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/testimonial04.jpg</image:loc>
        <image:title>IoT Projects Testimonial</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/box-icn3.jpg</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/specialization-gray-design.png</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/nakul-dogra-3-2/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/09/Nakul-Dogra-170x140.jpg</image:loc>
        <image:title>Nakul Dogra</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/roopa/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2017/04/IMG_0174.jpg</image:loc>
        <image:title>IMG_0174</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/saurabh-singh/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/07/Saurabh-170x140.png</image:loc>
        <image:title>Saurabh</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/success-stories/sanjiv-jha/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/05/Jha-153x140.png</image:loc>
        <image:title>Jha</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/in-img3-w.png</image:loc>
        <image:title>linkedin</image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/iot/iot-using-raspberry-pi</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2016/08/four_five_star.png</image:loc>
        <image:title>4.2 Star Rating: Very Good</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/prerequisites.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Monitor.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Calendar.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key2.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key4.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key5.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key3.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/key6.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-1.png</image:loc>
        <image:title></image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-2.png</image:loc>
        <image:title>Interfacing Hardware with the Raspberry Pi</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-3.png</image:loc>
        <image:title>Machine-to-Machine Communication with IoT</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-4.png</image:loc>
        <image:title>IoT Projects using Raspberry Pi</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/timeline-5.png</image:loc>
        <image:title>Speech Processing Concepts</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/capstone-project-icon.png</image:loc>
        <image:title>Capstone Project using Raspberry Pi</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-IOT-Hardware-Kit.png</image:loc>
        <image:title>IoT Hardware Kit</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/Catalyst.png</image:loc>
        <image:title>IoT Pre-Recorded Lectures</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Jigsaw-Learning-Center.png</image:loc>
        <image:title>Jigsaw Academy Learning Center</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/spe-Faculty-Support.png</image:loc>
        <image:title>IoT Faculty Support</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-harikrishna.jpg</image:loc>
        <image:title>Jigsaw Academy Linkedin Icon</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/jaws/common/iot/images/expert-urmil.jpg</image:loc>
        <image:title></image:title>
      </image:image>
  </url>
  <url>
    <loc>https://www.jigsawacademy.com/do-programmers-have-it-easier-when-it-comes-to-analytics/</loc>
    <lastmod>2017-11-08</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/themes/jigsaw/images/view-icon-white.png</image:loc>
        <image:title>comment</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/14-Why-learning-both-SAS-R-can-do-wonders-for-your-career-400x222.png</image:loc>
        <image:title>14-Why learning both SAS &amp; R can do wonders for your career</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/4-5-essential-skills-for-a-big-data-analyst-400x222.png</image:loc>
        <image:title>4-5 essential skills for a big data analyst</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/1-What-is-analytics-400x222.png</image:loc>
        <image:title>1-What-is-analytics</image:title>
      </image:image>
      <image:image>
        <image:loc>https://www.jigsawacademy.com/wp-content/uploads/2015/11/8-Do-programmers-have-it-easier-when-it-comes-to-analytics1-400x222.png</image:loc>
        <image:title>8-Do-programmers-have-it-easier-when-it-comes-to-analytics</image:title>
      </image:image>
  </url>
</urlset>